package com.tourisain.weijian.presentation.icons

import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import androidx.compose.material.icons.outlined.*
import androidx.compose.material.icons.rounded.*
import androidx.compose.material.icons.sharp.*
import androidx.compose.material.icons.twotone.*
import androidx.compose.ui.graphics.vector.ImageVector
@Suppress("DEPRECATION")
object LucideToMaterial {
    val ArrowLeft: ImageVector = Icons.Default.ArrowBack
    val ArrowUpDown: ImageVector = Icons.Default.SwapVert
    val Bell: ImageVector = Icons.Default.Notifications
    val Book: ImageVector = Icons.Default.Book
    val Calendar: ImageVector = Icons.Default.CalendarToday
    val CalendarClock: ImageVector = Icons.Default.Schedule
    val ChartBar: ImageVector = Icons.Default.BarChart
    val Check: ImageVector = Icons.Default.Check
    val ChevronDown: ImageVector = Icons.Default.ArrowDropDown
    val ChevronLeft: ImageVector = Icons.Default.ChevronLeft
    val ChevronRight: ImageVector = Icons.Default.ChevronRight
    val ChevronUp: ImageVector = Icons.Default.KeyboardArrowUp
    val Circle: ImageVector = Icons.Default.Circle
    val Clock: ImageVector = Icons.Default.AccessTime
    val Cloud: ImageVector = Icons.Default.Cloud
    val Copy: ImageVector = Icons.Default.ContentCopy
    val Download: ImageVector = Icons.Default.Download
    val Droplets: ImageVector = Icons.Default.WaterDrop
    val EllipsisVertical: ImageVector = Icons.Default.MoreVert
    val Eraser: ImageVector = Icons.Default.Delete
    val Eye: ImageVector = Icons.Default.RemoveRedEye
    val EyeOff: ImageVector = Icons.Default.VisibilityOff
    val File: ImageVector = Icons.Default.InsertDriveFile
    val FilePlus: ImageVector = Icons.Default.AddBox
    val FileText: ImageVector = Icons.Default.InsertDriveFile
    val Folder: ImageVector = Icons.Default.Folder
    val FolderOpen: ImageVector = Icons.Default.FolderOpen
    val Github: ImageVector = Icons.Default.Code
    val Globe: ImageVector = Icons.Default.Public
    val House: ImageVector = Icons.Default.Home
    val Image: ImageVector = Icons.Default.Image
    val Info: ImageVector = Icons.Default.Info
    val Key: ImageVector = Icons.Default.VpnKey
    val Layers: ImageVector = Icons.Default.Layers
    val LayoutGrid: ImageVector = Icons.Default.Apps
    val Leaf: ImageVector = Icons.Default.Star
    val List: ImageVector = Icons.Default.List
    val ListFilter: ImageVector = Icons.Default.FilterList
    val Lock: ImageVector = Icons.Default.Lock
    val Unlock: ImageVector = Icons.Default.LockOpen
    val Mail: ImageVector = Icons.Default.Email
    val Menu: ImageVector = Icons.Default.Menu
    val MessageCircle: ImageVector = Icons.Default.Chat
    val MessageSquare: ImageVector = Icons.Default.Chat
    val Minus: ImageVector = Icons.Default.Remove
    val MoveHorizontal: ImageVector = Icons.Default.DragIndicator
    val Music: ImageVector = Icons.Default.MusicNote
    val Package: ImageVector = Icons.Default.Work
    val Palette: ImageVector = Icons.Default.Palette
    val Pause: ImageVector = Icons.Default.Pause
    val Pencil: ImageVector = Icons.Default.Edit
    val PenLine: ImageVector = Icons.Default.Create
    val PiggyBank: ImageVector = Icons.Default.AccountBalanceWallet
    val Play: ImageVector = Icons.Default.PlayArrow
    val Plus: ImageVector = Icons.Default.Add
    val Redo: ImageVector = Icons.Default.Redo
    val RefreshCw: ImageVector = Icons.Default.Refresh
    val RotateCcw: ImageVector = Icons.Default.RotateLeft
    val Save: ImageVector = Icons.Default.Save
    val Search: ImageVector = Icons.Default.Search
    val Settings: ImageVector = Icons.Default.Settings
    val Share2: ImageVector = Icons.Default.Share
    val Shield: ImageVector = Icons.Default.Shield
    val Smile: ImageVector = Icons.Default.SentimentSatisfied
    val Smartphone: ImageVector = Icons.Default.Smartphone
    val Sparkles: ImageVector = Icons.Default.Star
    val Square: ImageVector = Icons.Default.Square
    val Star: ImageVector = Icons.Default.Star
    val StickyNote: ImageVector = Icons.Default.Note
    val Tag: ImageVector = Icons.Default.Label
    val ThumbsUp: ImageVector = Icons.Default.ThumbUp
    val Timer: ImageVector = Icons.Default.Timer
    val Trash: ImageVector = Icons.Default.Delete
    val Trash2: ImageVector = Icons.Default.DeleteForever
    val Type: ImageVector = Icons.Default.TextFormat
    val Undo: ImageVector = Icons.Default.Undo
    val Upload: ImageVector = Icons.Default.Upload
    val User: ImageVector = Icons.Default.Person
    val Video: ImageVector = Icons.Default.VideoLibrary
    val Wallet: ImageVector = Icons.Default.Wallet
    val X: ImageVector = Icons.Default.Close
    val Zap: ImageVector = Icons.Default.Star
    val AlignJustify: ImageVector = Icons.Default.FormatAlignJustify
    val AlignLeft: ImageVector = Icons.Default.FormatAlignLeft
    val Archive: ImageVector = Icons.Default.Archive
    val Bold: ImageVector = Icons.Default.FormatBold
    val FormatSize: ImageVector = Icons.Default.FormatSize
    val Frown: ImageVector = Icons.Default.SentimentDissatisfied
    val Italic: ImageVector = Icons.Default.FormatItalic
    val Strikethrough: ImageVector = Icons.Default.StrikethroughS
    val Link: ImageVector = Icons.Default.InsertLink
    val Table: ImageVector = Icons.Default.GridOn
    val TreeDeciduous: ImageVector = Icons.Default.Star
    val TreePine: ImageVector = Icons.Default.Star
}
object Lucide {
    val ArrowLeft = LucideToMaterial.ArrowLeft
    val ArrowUpDown = LucideToMaterial.ArrowUpDown
    val Bell = LucideToMaterial.Bell
    val Book = LucideToMaterial.Book
    val Calendar = LucideToMaterial.Calendar
    val CalendarClock = LucideToMaterial.CalendarClock
    val ChartBar = LucideToMaterial.ChartBar
    val Check = LucideToMaterial.Check
    val ChevronDown = LucideToMaterial.ChevronDown
    val ChevronLeft = LucideToMaterial.ChevronLeft
    val ChevronRight = LucideToMaterial.ChevronRight
    val ChevronUp = LucideToMaterial.ChevronUp
    val Circle = LucideToMaterial.Circle
    val Clock = LucideToMaterial.Clock
    val Cloud = LucideToMaterial.Cloud
    val Copy = LucideToMaterial.Copy
    val Download = LucideToMaterial.Download
    val Droplets = LucideToMaterial.Droplets
    val EllipsisVertical = LucideToMaterial.EllipsisVertical
    val Eraser = LucideToMaterial.Eraser
    val Eye = LucideToMaterial.Eye
    val EyeOff = LucideToMaterial.EyeOff
    val File = LucideToMaterial.File
    val FilePlus = LucideToMaterial.FilePlus
    val FileText = LucideToMaterial.FileText
    val Folder = LucideToMaterial.Folder
    val FolderOpen = LucideToMaterial.FolderOpen
    val Github = LucideToMaterial.Github
    val Globe = LucideToMaterial.Globe
    val House = LucideToMaterial.House
    val Image = LucideToMaterial.Image
    val Info = LucideToMaterial.Info
    val Key = LucideToMaterial.Key
    val Layers = LucideToMaterial.Layers
    val LayoutGrid = LucideToMaterial.LayoutGrid
    val Leaf = LucideToMaterial.Leaf
    val Link = LucideToMaterial.Link
    val List = LucideToMaterial.List
    val ListFilter = LucideToMaterial.ListFilter
    val Lock = LucideToMaterial.Lock
    val Unlock = LucideToMaterial.Unlock
    val Mail = LucideToMaterial.Mail
    val Menu = LucideToMaterial.Menu
    val MessageCircle = LucideToMaterial.MessageCircle
    val MessageSquare = LucideToMaterial.MessageSquare
    val Minus = LucideToMaterial.Minus
    val MoveHorizontal = LucideToMaterial.MoveHorizontal
    val Music = LucideToMaterial.Music
    val Package = LucideToMaterial.Package
    val Palette = LucideToMaterial.Palette
    val Pause = LucideToMaterial.Pause
    val Pencil = LucideToMaterial.Pencil
    val PenLine = LucideToMaterial.PenLine
    val PiggyBank = LucideToMaterial.PiggyBank
    val Play = LucideToMaterial.Play
    val Plus = LucideToMaterial.Plus
    val Redo = LucideToMaterial.Redo
    val RefreshCw = LucideToMaterial.RefreshCw
    val RotateCcw = LucideToMaterial.RotateCcw
    val Save = LucideToMaterial.Save
    val Search = LucideToMaterial.Search
    val Settings = LucideToMaterial.Settings
    val Share2 = LucideToMaterial.Share2
    val Shield = LucideToMaterial.Shield
    val Smile = LucideToMaterial.Smile
    val Smartphone = LucideToMaterial.Smartphone
    val Sparkles = LucideToMaterial.Sparkles
    val Square = LucideToMaterial.Square
    val Star = LucideToMaterial.Star
    val StickyNote = LucideToMaterial.StickyNote
    val Table = LucideToMaterial.Table
    val Tag = LucideToMaterial.Tag
    val ThumbsUp = LucideToMaterial.ThumbsUp
    val Timer = LucideToMaterial.Timer
    val Trash = LucideToMaterial.Trash
    val Trash2 = LucideToMaterial.Trash2
    val Type = LucideToMaterial.Type
    val Undo = LucideToMaterial.Undo
    val Upload = LucideToMaterial.Upload
    val User = LucideToMaterial.User
    val Video = LucideToMaterial.Video
    val Wallet = LucideToMaterial.Wallet
    val X = LucideToMaterial.X
    val Zap = LucideToMaterial.Zap
    val AlignJustify = LucideToMaterial.AlignJustify
    val AlignLeft = LucideToMaterial.AlignLeft
    val Archive = LucideToMaterial.Archive
    val Bold = LucideToMaterial.Bold
    val FormatSize = LucideToMaterial.FormatSize
    val Frown = LucideToMaterial.Frown
    val Italic = LucideToMaterial.Italic
    val Strikethrough = LucideToMaterial.Strikethrough
    val TreeDeciduous = LucideToMaterial.TreeDeciduous
    val TreePine = LucideToMaterial.TreePine
}


